export type CSSObject = { [key: string]: any };
export type StyleMapEntry = { [key: string]: string };
export interface CssStringHolder {
	main: string[];
	media: string[];
}
export interface HTMLAttributes {
	inline: CSSObject;
	accesskey?: string;
	class?: string;
	className?: string;
	contenteditable?: string;
	'data-*'?: string;
	dir?: string;
	draggable?: string;
	hidden?: string;
	id?: string;
	lang?: string;
	style?: string;
	tabindex?: string;
	title?: string;
	translate?: string;

	onabort?: (e?: any) => any;
	onautocomplete?: (e?: any) => any;
	onautocompleteerror?: (e?: any) => any;
	onblur?: (e?: any) => any;
	oncancel?: (e?: any) => any;
	oncanplay?: (e?: any) => any;
	oncanplaythrough?: (e?: any) => any;
	onchange?: (e?: any) => any;
	onClick?: (e?: any) => any;
	onChange?: (e?: any) => any;
	onBlur?: (e?: any) => any;
	onclick?: (e?: any) => any;
	onclose?: (e?: any) => any;
	oncontextmenu?: (e?: any) => any;
	oncopy?: (e?: any) => any;
	oncuechange?: (e?: any) => any;
	oncut?: (e?: any) => any;
	ondblclick?: (e?: any) => any;
	ondrag?: (e?: any) => any;
	ondragend?: (e?: any) => any;
	ondragenter?: (e?: any) => any;
	ondragexit?: (e?: any) => any;
	ondragleave?: (e?: any) => any;
	ondragover?: (e?: any) => any;
	ondragstart?: (e?: any) => any;
	ondrop?: (e?: any) => any;
	ondurationchange?: (e?: any) => any;
	onemptied?: (e?: any) => any;
	onended?: (e?: any) => any;
	onerror?: (e?: any) => any;
	onfocus?: (e?: any) => any;
	oninput?: (e?: any) => any;
	oninvalid?: (e?: any) => any;
	onkeydown?: (e?: any) => any;
	onkeypress?: (e?: any) => any;
	onkeyup?: (e?: any) => any;
	onload?: (e?: any) => any;
	onloadeddata?: (e?: any) => any;
	onloadedmetadata?: (e?: any) => any;
	onloadstart?: (e?: any) => any;
	onmousedown?: (e?: any) => any;
	onmouseenter?: (e?: any) => any;
	onmouseleave?: (e?: any) => any;
	onmousemove?: (e?: any) => any;
	onmouseout?: (e?: any) => any;
	onmouseover?: (e?: any) => any;
	onmouseup?: (e?: any) => any;
	onmousewheel?: (e?: any) => any;
	onpaste?: (e?: any) => any;
	onpause?: (e?: any) => any;
	onplay?: (e?: any) => any;
	onplaying?: (e?: any) => any;
	onprogress?: (e?: any) => any;
	onratechange?: (e?: any) => any;
	onreset?: (e?: any) => any;
	onresize?: (e?: any) => any;
	onscroll?: (e?: any) => any;
	onseeked?: (e?: any) => any;
	onseeking?: (e?: any) => any;
	onselect?: (e?: any) => any;
	onshow?: (e?: any) => any;
	onstalled?: (e?: any) => any;
	onsubmit?: (e?: any) => any;
	onsuspend?: (e?: any) => any;
	ontimeupdate?: (e?: any) => any;
	ontoggle?: (e?: any) => any;
	onvolumechange?: (e?: any) => any;
	onwaiting?: (e?: any) => any;
	onwheel?: (e?: any) => any;

	accept?: string;
	'accept-charset'?: string;
	action?: string;
	align?: string;
	alt?: string;
	autocomplete?: string;
	autofocus?: string;
	checked?: string;
	disabled?: string;
	enctype?: string;
	for?: string;
	form?: string;
	formaction?: string;
	formenctype?: string;
	formmethod?: string;
	formnovalidate?: string;
	formtarget?: string;
	height?: string;
	list?: string;
	max?: string;
	maxlength?: string;
	min?: string;
	minlength?: string;
	multiple?: string;
	name?: string;
	novalidate?: string;
	pattern?: string;
	placeholder?: string;
	readonly?: string;
	required?: string;
	selected?: string;
	size?: string;
	src?: string;
	step?: string;
	target?: string;
	value?: string;
	defaultValue?: string;
	width?: string;

	autoplay?: string;
	buffered?: string;
	controls?: string;
	crossorigin?: string;
	loop?: string;
	muted?: string;
	playsinline?: string;
	poster?: string;
	preload?: string;
	volume?: string;

	charset?: string;
	content?: string;
	href?: string;
	hreflang?: string;
	'http-equiv'?: string;
	media?: string;
	rel?: string;
	rev?: string;
	sizes?: string;
	srcset?: string;
	type?: string;
}
